# Generated by Django 5.2.1 on 2026-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
