# Generated by Django 5.2.1 on 2026-01-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ImageField(default='', upload_to='links_page/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
