# Generated by Django 5.2.1 on 2026-01-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_link_icon_name_link_icon_alter_link_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(null=True, upload_to='links_page/'),
        ),
    ]
