# Generated by Django 5.2.1 on 2026-01-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='links_page/'),
        ),
    ]
