# Generated by Django 5.2.1 on 2026-01-06 06:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_link_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=255)),
                ('description', tinymce.models.HTMLField(default='')),
            ],
        ),
    ]
