# Generated by Django 5.2.1 on 2025-12-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instruction_manual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productinstruction'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standards_and_approval',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
