# Generated by Django 5.2.1 on 2025-12-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_productcategory_for_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.CreateModel(
            name='ProductDetailsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
