# Generated by Django 5.2.1 on 2025-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcategory_options_remove_product_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productdetailsitem',
            options={'verbose_name': 'Product Details', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='standards_and_approval',
            field=models.TextField(blank=True, null=True),
        ),
    ]
