# Generated by Django 5.2.1 on 2025-12-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productvolume',
            options={'verbose_name': 'Volume', 'verbose_name_plural': 'Volumes'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='for_volume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.productvolume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='IMPORTANT for product URL, QR code.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productvolume',
            name='name',
            field=models.CharField(help_text='Example: 1L, 4L, etc.', max_length=50, unique=True),
        ),
    ]
