# Generated by Django 5.2.1 on 2025-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstruction',
            name='pdf_manual',
            field=models.FileField(blank=True, null=True, upload_to='product_manuals/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='vehicles/'),
        ),
    ]
