# Generated by Django 5.2.1 on 2025-12-04 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productinstruction_pdf_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instruction_manual',
        ),
        migrations.AddField(
            model_name='productinstruction',
            name='for_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
