# Generated by Django 5.2.1 on 2025-12-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_instruction_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstruction',
            name='for_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
