# Generated by Django 5.2.1 on 2025-12-04 06:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productinstruction_for_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suitable_for',
            new_name='suitable_vehicles',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='standards_and_approval',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
