# Generated by Django 5.2.1 on 2025-12-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_suitable_for_product_suitable_vehicles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='volume',
            new_name='volumes',
        ),
    ]
