# Generated by Django 5.2.1 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_volume_product_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product'),
        ),
    ]
