# Generated by Django 5.2.1 on 2025-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productcategory_for_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='for_product',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcategory'),
        ),
    ]
