# Generated by Django 5.2.1 on 2025-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productcategory_for_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
