# Generated by Django 5.2.1 on 2025-12-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_productcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productinstruction',
            options={'verbose_name': 'Product Instruction', 'verbose_name_plural': 'Product Instructions'},
        ),
    ]
