# Generated by Django 5.2.1 on 2025-12-04 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
