# Generated by Django 5.2.1 on 2025-12-04 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_vehicle_date_created_vehicle_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
