# Generated by Django 5.2.1 on 2025-12-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='for_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='products.productvolume'),
        ),
    ]
