# Generated by Django 5.2.1 on 2025-12-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productimage_for_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volumes',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvolume')),
            ],
            options={
                'verbose_name': 'Product Variant (volume & price)',
                'verbose_name_plural': 'Product Variants (volume & price)',
                'unique_together': {('product', 'volume')},
            },
        ),
    ]
