# Generated by Django 5.2.1 on 2025-12-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_price_remove_product_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volumes',
            field=models.ManyToManyField(blank=True, related_name='product_volumes', through='products.ProductVariant', to='products.productvolume'),
        ),
    ]
