# Generated by Django 5.2.1 on 2025-12-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailsitem',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='products.product'),
        ),
    ]
