# Generated by Django 5.2.1 on 2025-12-20 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productdetailsitem_for_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstruction',
            name='for_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='products.product'),
        ),
    ]
