# Generated by Django 5.2.1 on 2026-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
