# Generated by Django 5.2.1 on 2026-02-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_order_is_resolved_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
